source 'https://github.com/wax2045/NNSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNHomeKit_Example' do
  pod 'NNHomeKit', :path => '../'

  target 'NNHomeKit_Tests' do
    inherit! :search_paths

    
  end
end
